call plug#begin()
Plug 'morhetz/gruvbox'
Plug 'jiangmiao/auto-pairs'
Plug 'dense-analysis/ale'
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

" basic
set number
set autoindent
set list
set listchars=trail:·
set cursorline
set expandtab
set history=100

nnoremap <silent> <C-h> :bp <CR>
nnoremap <silent> <C-l> :bn <CR>
nnoremap <silent> <C-c> :bd <CR>

syntax on
set background=dark
set t_Co=256
colorscheme gruvbox

" search
set hlsearch
set incsearch
set ignorecase
set smartcase

" fold
set foldmethod=indent
set foldlevel=99
nnoremap <space> za <CR>

au BufNewFile,BufRead *.py
        \ set tabstop=4 |
        \ set softtabstop=4 |
        \ set shiftwidth=4 |
        \ set textwidth=79

au BufNewFile,BufRead *.php,*.json,*.js
        \ set tabstop=4 |
        \ set softtabstop=4 |
        \ set shiftwidth=4

au BufNewFile,BufRead *.sh
        \ set tabstop=2 |
        \ set softtabstop=2 |
        \ set shiftwidth=2

" netrw
let g:netrw_banner=0
let g:netrw_liststyle=3
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_winsize=25
let g:netrw_list_hide='.*\.swp$,\(^\|\s\s\)\zs\.\S\+'

nnoremap <silent> <C-a> :call NetrwToggle() <CR>
function! NetrwToggle()
        let i = bufnr("$")
        let wasOpen = 0
        while (i >= 1)
            if (getbufvar(i, "&filetype") == "netrw")
                silent exe "bwipeout " . i
                let wasOpen = 1
            endif
            let i-=1
        endwhile
    if !wasOpen
        silent Lexplore
    endif
endfunction

" airline
set laststatus=2
set ttimeoutlen=50
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline_theme='papercolor'

" auto-pair
let g:AutoPairsFlyMode = 1
